#!/bin/bash
######################Phileserve Creation Script For Raspberry Pi 2############################
clear
red='\e[0;31m'
NC='\e[0m'

# Deleting alarm user and changing Root password
echo -e "${red}Deleting alarm user...${NC}" 
su
cd /root
userdel -r alarm
echo -e "${red}Change the root password...${NC}" 
passwd

# Changing hostname
echo -e "${red}Changing your hostname...${NC}" 
hostnamectl set-hostname phileserve

# /etc/motd text
echo -e "${red}Downloading sample /etc/motd file...${NC}" 
wget https://raw.githubusercontent.com/archphile/phileserve/master/files/motd-phileserve -O /etc/motd
nano /etc/motd

# Changing DNS servers
echo -e "${red}Changing to Google DNS servers...${NC}" 
systemctl disable systemd-resolved
systemctl mask systemd-resolved
rm /etc/resolv.conf
cat > /etc/resolv.conf <<"EOF"
# Google DNS
nameserver 8.8.8.8
nameserver 8.8.4.4
# Opendns
#nameserver 208.67.222.222 
#nameserver 208.67.220.220
EOF
echo -e "${red}Disallowing dhcpcd to change DNS servers...${NC}" 
echo "nohook resolv.conf" >>/etc/dhcpcd.conf

# Network Configuration
echo -e "${red}Changing netctl network configuration...${NC}" 
wget https://raw.githubusercontent.com/archphile/phileserve/master/files/phileserve-network -O /etc/netctl/phileserve-network
systemctl disable systemd-networkd
systemctl mask systemd-networkd
netctl enable phileserve-network

# Disabling ipv6
# "net.ipv6.conf.all.disable_ipv6=1" added throught archphile-optimize package 
sed -e '/::1/ s/^#*/#/' -i /etc/hosts
echo >>/etc/dhcpcd.conf
echo "#Disable ipv6 connectivity" >>/etc/dhcpcd.conf
echo "noipv6rs" >>/etc/dhcpcd.conf
echo "noipv6" >>/etc/dhcpcd.conf

# Locale and timezone configuration
systemctl disable systemd-timesyncd
systemctl mask systemd-timesyncd
pacman -Sy ntp --noconfirm
echo -e "${red}Changing locale, timezone and ntp configuration...${NC}" 
sed -i 's/^#en_US.UTF-8 UTF-8.*/en_US.UTF-8 UTF-8/' /etc/locale.gen
locale-gen
echo "LANG="en_US.UTF-8"" > /etc/locale.conf
rm /etc/localtime
ln -s /usr/share/zoneinfo/Europe/Athens /etc/localtime
wget https://raw.githubusercontent.com/archphile/phileserve/master/files/ntp.conf -O /etc/ntp.conf

# /etc/fstab tweaking and linking .bash_history to /dev/null
echo -e "${red}Changing fstab entries...${NC}" 
wget https://raw.githubusercontent.com/archphile/phileserve/master/files/fstab -O /etc/fstab
echo -e "${red}Linking .bash_history to /dev/null...${NC}" 
rm /root/.bash_history
ln -sf /dev/null ~/.bash_history

# Installing needed packages
echo -e "${red}Updating system and installing needed packages...${NC}" 
pacman -Syu --noconfirm
pacman -S samba cifs-utils nfs-utils transmission-cli udevil ntfs-3g hfsprogs hdparm hd-idle htop smartmontools rsync  --noconfirm

# Removing unneeded packages and cleaning pacman cache
echo -e "${red}Removing unneeded packages and cleaning pacman cache...${NC}" 
pacman -Rcsn lvm2 mdadm reiserfsprogs xfsprogs man-db --noconfirm
#systemctl disable cronie
#systemctl mask cronie
pacman -Scc

# Setting multi-user.target as the new default target
echo -e "${red}Setting default systemd target...${NC}" 
systemctl set-default -f multi-user.target

# Samba configuration
echo -e "${red}Configuring  and enabling samba server...${NC}" 
wget https://raw.githubusercontent.com/archphile/phileserve/master/files/smb.conf -O /etc/samba/smb.conf
useradd nash -m -G users
passwd nash
smbpasswd -a nash
systemctl enable smbd nmbd

# NFS configuration
echo -e "${red}Configuring NFS server...${NC}" 
mkdir -p /srv/nfs4/phileserve
wget https://raw.githubusercontent.com/archphile/phileserve/master/files/exports -O /etc/exports

# udevil configuration
echo -e "${red}Creating udevil configuration and enabling devmon service...${NC}" 
wget https://raw.githubusercontent.com/archphile/phileserve/master/files/udevil.conf -O /etc/udevil/udevil.conf
mkdir /mnt/usb-disks
systemctl enable devmon@root

# disks spin-down configuration
echo -e "${red}Fetching udev rules for hdparm...${NC}" 
mkdir /opt/phileserve
wget https://raw.githubusercontent.com/archphile/phileserve/master/files/50-hdparm.rules-onedisk -O /opt/phileserve/50-hdparm.rules-onedisk
wget https://raw.githubusercontent.com/archphile/phileserve/master/files/50-hdparm.rules-manydisks -O /opt/phileserve/50-hdparm.rules-manydisks
wget https://raw.githubusercontent.com/archphile/phileserve/master/files/hd-idle -O /etc/conf.d/hd-idle

#minidlna configuration
#echo -e "${red}Fetching dlna configuration...${NC}" 
#wget https://raw.githubusercontent.com/archphile/phileserve/master/files/minidlna.conf -O /etc/minidlna.conf

# journald.conf configuration and /var/log deletion
echo -e "${red}Changing journald.conf configuration and deleting /var/log...${NC}" 
sed -i 's/^#Storage=auto.*/Storage=none/' /etc/systemd/journald.conf
#systemctl disable systemd-journald
#systemctl mask systemd-journald
#systemctl mask systemd-journal-flush.service
rm -R /var/log

# increase ssh security
#echo -e "${red}Changing default ssh port to 667...${NC}" 
#sed -i 's/^#Port 22.*/Port 667/' /etc/ssh/sshd_config

# changing /etc/issue message
echo -e "${red}Changing /etc/issue message ...${NC}" 
echo "Phileserve \r (\l)" > /etc/issue

# change the password at first login
echo -e "${red}Setting a password change for next login...${NC}" 
chage -d 0 root

#fixing root permissions for sshd
echo -e "${red}Setting PermitRootLogin to yes...${NC}" 
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

# system cleanup
echo -e "${red}Cleaning up system...${NC}" 
rm /etc/ssh/ssh_host_*
rm /root/phileserve-create-script*

echo -e "${red}PLEASE REBOOT YOUR SYSTEM IMMEDIATELY!!!!!!${NC}" 
